### ISSUE TITLE
add scripts

### ISSUE THREAD

**Issue by ajschumacher** [chriswhong/justinGrimesGeojson#1]
:see_no_evil:

**Comment by chriswhong** [comment]
I should have been clearer, the script is just the Javascript in index.html, and it outputs the geojson into a textarea and renders it on a leaflet map

**Comment by ajschumacher** [comment]
haha ah yes, javascript... :trollface: I just wanted to make some comment because I was so excited to see more Grimes-related work being done. Has Justin seen this already? I don't want to @ him if you're planning a surprise (not that this repo is private or anything~)

**Comment by chriswhong** [comment]
Yeah he favorited it today!  Share at will.  Better yet, transform the
polygons and recast him elsewhere on planet earth.

**Comment by ajschumacher** [comment]
:earth_africa: :earth_americas: :earth_asia: :grimes:
